name: VineCraft-LostSheep
main: world.vinecraft.lostsheep.LostSheepPladdon
version: ${project.version}${build.number}
api-version: "1.21"

authors: [tastybento]
contributors: ["The VineCraft Community"]
website: https://vinecraft.world
description: ${project.description}
